name:  CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    #- run: pm2 kill
    #- run: pm2 start index.js
    
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        key: ${{ secrets.TEST }}
        host: 15.207.86.236
        username: ubuntu
        port: 22
        source: "*"
        target: "/home/ubuntu/test/"
         
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.TEST }}
        host: 15.207.86.236
        username: ubuntu
        port: 22
        script: |
          cd
          cd test/
          # npm install
          pm2 restart ./dist/src/main.js
        #proxy_port: 8000
